# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sheekha Jariwala
tagline:          'A Jekyll theme'
description:      'Computer-Science Grad | Bibliophile'
url:              http://sheekhaj.github.io
# baseurl:          /

plugins:          [jekyll-paginate]

author:
  name:           'Sheekha Jariwala'
  github:         'SheekhaJ'
  linkedin:       'sheekhajariwala'
  twitter:        'ShikhaJariwla'
  goodreads:      'sheekhajariwala'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/SheekhaJ/SheekhaJ.github.io
