# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sheekha Jariwala
tagline:          'A Jekyll theme'
description:      'Computer-Science grad | Bibliophile'
url:              http://hyde.getpoole.com
baseurl:          /

plugins:          [jekyll-paginate]

author:
  name:           'Sheekha Jariwala'
  url:            https://twitter.com/ShikhaJariwla

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/SheekhaJ/SheekhaJ.github.io
